// Human-readable names for each scene id, shared by the breadcrumb bar
// and by any scene that needs to say "back to <caller screen>".
export const SCENE_LABELS = {
  title: "タイトル画面",
  saveSlot: "セーブスロット画面",
  options: "オプション画面",
  pause: "ポーズ画面",
  world: "ワールド画面",
  map: "マップ画面",
  episode: "エピソード画面",
  battle: "戦闘画面",
  exploration: "探索画面",
  trade: "取引画面",
  warehouse: "倉庫画面",
  gallery: "ギャラリー画面",
  squadFormation: "部隊編成画面",
  weaponStorage: "武器置き場画面",
  resourceStorage: "荷物置き場画面",
  coatingStorage: "糖衣置き場画面",
  coatingEdit: "糖衣編集画面",
  smithy: "鍛冶画面",
  weaponForge: "武器製造画面",
  weaponEnhance: "武器強化画面",
  weaponTrade: "武器取引画面",
  tailorShop: "仕立画面",
  timeEats: "軽食画面",
  maturation: "熟成画面",
  hiring: "雇用画面",
  peddlerShop: "行商画面",
  resourceTrade: "資源取引画面",
  result: "リザルト画面",
};
